#!/usr/bin/bash

CFLAGS=${CFLAGS:-""}
CC=${CC:-cc}
$CC $CFLAGS escrow.c -c -o escrow.o
$CC $CFLAGS echo-server.c escrow.o -o echo-server
$CC $CFLAGS echo-client.c -o echo-client
$CC $CFLAGS escrow.o main.c -o escrowd 
